# DO NOT EDIT THIS FILE!
#
# Python module svcUrg__POA generated by omniidl

import omniORB
omniORB.updateModule("svcUrg__POA")

# ** 1. Stub files contributing to this module
import UrgService_idl

# ** 2. Sub-modules

# ** 3. End
