# DO NOT EDIT THIS FILE!
#
# Python module svcEnsenso generated by omniidl

import omniORB
omniORB.updateModule("svcEnsenso")

# ** 1. Stub files contributing to this module
import EnsensoService_idl

# ** 2. Sub-modules

# ** 3. End
