# DO NOT EDIT THIS FILE!
#
# Python module svcUrg generated by omniidl

import omniORB
omniORB.updateModule("svcUrg")

# ** 1. Stub files contributing to this module
import UrgService_idl

# ** 2. Sub-modules

# ** 3. End
