# DO NOT EDIT THIS FILE!
#
# Python module myHRP generated by omniidl

import omniORB
omniORB.updateModule("myHRP")

# ** 1. Stub files contributing to this module
import hiroJointControl_idl

# ** 2. Sub-modules

# ** 3. End
