# DO NOT EDIT THIS FILE!
#
# Python module OpenHRP__POA generated by omniidl

import omniORB
omniORB.updateModule("OpenHRP__POA")

# ** 1. Stub files contributing to this module
import ArmControlService_idl
import DataLoggerService_idl
import GrasperService_idl
import RobotHardwareService_idl
import SequencePlayerService_idl
import SystemAdminService_idl
import TimeKeeperService_idl

# ** 2. Sub-modules

# ** 3. End
